version: '3.9'

services:
  app:
    build:
      context: .
      args:
        # If we're running using this docker compose which we're only going to be using for develop, set a build argument called "DEV" to true
        - DEV=true
    container_name: RecipeAPI
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    # This is the command used to run the service. We can override it when we run docker-compose run
    # If we don't specify this option it's going to use the command define in the Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    # Telling compose the app service depends on the db service
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: PostgresQL
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

# To store persistent data using compose, Allow us to map a directory inside the Container to dir in local machine
volumes:
  dev-db-data:
