---
# The name that will appear in Github actions
name: Checks

# This is the trigger
on: [push]

# Defining the jobs
jobs:
  # Job's ID
  test-lint:
    # Job's name
    name: Test and Lint
    # Runner that we're going to be running our job on
    runs-on: ubuntu-20.04
    # Steps are the diff things that run for the job
    steps:
      # First step of our job - Logging to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Action provided by Github auto, checks our code out inside Github actions job 
      - name: Checkout
        uses: actions/checkout@v2
      # Run our tests
      - name: Test
        # Command used for running the tests on our project
        run: docker-compose run --rm RecipeAPI sh -c "python manage.py test"
      # Run the linting
      - name: Linting
        run: docker-compose run --rm app sh -c "flake8"
